config/routes.rb
Rails.application.routes.draw do
  resources :photos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'homes#index'
  get 'details' => 'homes#details'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def index
		
	end
	def details
		
	end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]

  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url, notice: 'Photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:photo_name, :description, :photo_size)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Photoblock</title>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Favicon -->
    <link rel="icon" type="image/png" href="https://strictcity.live/photoblock/madsparrow.me/emily/assets/images/ico/favicon.png" />
    <!-- CSS Plugins -->
    <link rel="stylesheet" href="https://strictcity.live/photoblock/madsparrow.me/emily/assets/css/plugins.min.css">
    <!-- Custom CSS File -->
    <link rel="stylesheet" href="https://strictcity.live/photoblock/madsparrow.me/emily/assets/css/style.css">

  </head>

  <body>

    <%= yield %>

    <!-- JS Libraries -->
    <!-- jquery-2.1.3.min js -->
    <script type="text/javascript" src="https://strictcity.live/photoblock/madsparrow.me/emily/assets/js/jquery-3.2.1.min.js"></script>
    <!-- Vendors -->
    <script type="text/javascript" src="https://strictcity.live/photoblock/madsparrow.me/emily/assets/js/plugins.min.js"></script>
    <!-- Main js -->
    <script type="text/javascript" src="https://strictcity.live/photoblock/madsparrow.me/emily/assets/js/main.js"></script>
  </body>
</html>

app/views/photos/_form.html.erb
<body>
    <div class="ms-main-container loaded" style="opacity: 1;">
      <!-- Preloader -->
      <!-- Header -->
      <header class="ms-header">
        <nav class="ms-nav">
          <div class="ms-logo">
            <a href="/" data-type="page-transition">
              <div class="logo-dark current"><img src="https://strictcity.live/photoblock/madsparrow.me/emily/logo-dark.svg" alt="logo image"></div>
              <div class="logo-light"><img src="https://strictcity.live/photoblock/madsparrow.me/emily/logo-light.svg" alt="logo image"></div>
            </a>
          </div>
          
          </div>
        </nav>
      </header>
      <!-- Container -->
      <main class="ms-container" style="padding-top: 8em;">
        <!-- Page Title -->
        
        <!-- Page Content -->
        <div class="ms-section__block">
          <%= form_with(model: photo, local: true) do |form| %>

  <div class="field">
    <%= form.label :photo_name %>
    <%= form.text_field :photo_name, id: :photo_photo_name, :class => 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :photo_description %>
  </div>

  <div class="field">
    <%= form.label :photo_size %>
    <%= form.text_field :photo_size, id: :photo_photo_size %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %></div>
      </main>
      <!-- Footer -->
      <footer>
        <div class="ms-footer">
          <div class="copyright">Copyright © 2017. Design by <a href="https://twitter.com/sammyngn">SammyNGN</a></div>
          <ul class="socials">
            <li><a href="#" class="socicon-facebook"></a></li>
            <li><a href="#" class="socicon-twitter"></a></li>
            <li><a href="#" class="socicon-instagram"></a></li>
            <li><a href="#" class="socicon-youtube"></a></li>
          </ul>
        </div>
      </footer>
    </div>

</body>

app/views/photos/edit.html.erb
<h1>Editing Photo</h1>

<%= render 'form', photo: @photo %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Photos</h1>

<table>
  <thead>
    <tr>
      <th>Photo name</th>
      <th>Description</th>
      <th>Photo size</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @photos.each do |photo| %>
      <tr>
        <td><%= photo.photo_name %></td>
        <td><%= photo.description %></td>
        <td><%= photo.photo_size %></td>
        <td><%= link_to 'Show', photo %></td>
        <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
        <td><%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Photo', new_photo_path %>

app/views/photos/new.html.erb
<h1>New Photo</h1>

<%= render 'form', photo: @photo %>

<%= link_to 'Back', photos_path %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Photo name:</strong>
  <%= @photo.photo_name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @photo.description %>
</p>

<p>
  <strong>Photo size:</strong>
  <%= @photo.photo_size %>
</p>

<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', photos_path %>